# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/amaln/OneDrive - Danmarks Tekniske Universitet/3. Semester/Computerarkitektur/Final"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/amaln/OneDrive - Danmarks Tekniske Universitet/3. Semester/Computerarkitektur/Final"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/amaln/OneDrive - Danmarks Tekniske Universitet/3. Semester/Computerarkitektur/Final/CMakeFiles" "/mnt/c/Users/amaln/OneDrive - Danmarks Tekniske Universitet/3. Semester/Computerarkitektur/Final//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/amaln/OneDrive - Danmarks Tekniske Universitet/3. Semester/Computerarkitektur/Final/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named isasim

# Build rule for target.
isasim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 isasim
.PHONY : isasim

# fast build rule for target.
isasim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isasim.dir/build.make CMakeFiles/isasim.dir/build
.PHONY : isasim/fast

IsaSim.o: IsaSim.c.o
.PHONY : IsaSim.o

# target to build an object file
IsaSim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isasim.dir/build.make CMakeFiles/isasim.dir/IsaSim.c.o
.PHONY : IsaSim.c.o

IsaSim.i: IsaSim.c.i
.PHONY : IsaSim.i

# target to preprocess a source file
IsaSim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isasim.dir/build.make CMakeFiles/isasim.dir/IsaSim.c.i
.PHONY : IsaSim.c.i

IsaSim.s: IsaSim.c.s
.PHONY : IsaSim.s

# target to generate assembly for a file
IsaSim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isasim.dir/build.make CMakeFiles/isasim.dir/IsaSim.c.s
.PHONY : IsaSim.c.s

src/example.o: src/example.c.o
.PHONY : src/example.o

# target to build an object file
src/example.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isasim.dir/build.make CMakeFiles/isasim.dir/src/example.c.o
.PHONY : src/example.c.o

src/example.i: src/example.c.i
.PHONY : src/example.i

# target to preprocess a source file
src/example.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isasim.dir/build.make CMakeFiles/isasim.dir/src/example.c.i
.PHONY : src/example.c.i

src/example.s: src/example.c.s
.PHONY : src/example.s

# target to generate assembly for a file
src/example.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isasim.dir/build.make CMakeFiles/isasim.dir/src/example.c.s
.PHONY : src/example.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... isasim"
	@echo "... IsaSim.o"
	@echo "... IsaSim.i"
	@echo "... IsaSim.s"
	@echo "... src/example.o"
	@echo "... src/example.i"
	@echo "... src/example.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

